### ISSUE TITLE
自定义路由

### ISSUE THREAD

**Issue by MasterSJ** [polarismesh/website#349]
在配置自定义路由之后, 客户端拉取配置异常 
com.google.protobuf.InvalidProtocolBufferException: Cannot find type for url: type.googleapis.com/v1.RuleRoutingConfig
(spring-cloud-tencent-dependencies版本为1.11.7-2021.0.6, 服务端版本为1.17.1)

**Comment by chuntaojun** [comment]
这里实际测试了下没发现你说的这个问题

**Comment by MasterSJ** [comment]
我是配置了一条自定义路由, 规则是从A服务调用B服务时, 如果Header中包含ttt=aaa, 那么将转发至目标服务的一下实例分组featureenv=f2, 启用规则之后我在请求Header中手动添加ttt=aaa, 这是A服务就会报这个异常.
![image](https://github.com/polarismesh/website/assets/18444280/6f5223b4-6b04-4394-be94-5f63b7735e6d)
![image](https://github.com/polarismesh/website/assets/18444280/333f23bf-e723-41d4-b8bb-bb2994286bc1)

**Comment by chuntaojun** [comment]
可以给一完整的堆栈吗

**Comment by MasterSJ** [comment]
2023-06-15 16:44:31.462 [ERROR] [service-identity] [] [] [] [] c.t.p.p.r.memory.MessagePersistHandler   :fail to write file .\polaris\backup\svc#dev#service-identity#routing.yaml.tmp

com.google.protobuf.InvalidProtocolBufferException: Cannot find type for url: type.googleapis.com/v1.RuleRoutingConfig
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printAny(JsonFormat.java:882) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.access$1000(JsonFormat.java:710) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl$1.print(JsonFormat.java:783) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:762) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1258) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1123) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1048) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1026) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:765) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1258) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1123) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printRepeatedFieldValue(JsonFormat.java:1062) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1046) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1026) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:765) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1258) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1123) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1048) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1026) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:765) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$Printer.appendTo(JsonFormat.java:368) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$Printer.print(JsonFormat.java:378) ~[protobuf-java-util-3.21.7.jar:na]
	at com.tencent.polaris.plugins.registry.memory.MessagePersistHandler.doWriteTmpFile(MessagePersistHandler.java:207) [registry-memory-1.12.9.jar:na]
	at com.tencent.polaris.plugins.registry.memory.MessagePersistHandler.writeTmpFile(MessagePersistHandler.java:193) [registry-memory-1.12.9.jar:na]
	at com.tencent.polaris.plugins.registry.memory.MessagePersistHandler.doSaveService(MessagePersistHandler.java:229) [registry-memory-1.12.9.jar:na]
	at com.tencent.polaris.plugins.registry.memory.MessagePersistHandler.saveService(MessagePersistHandler.java:144) [registry-memory-1.12.9.jar:na]
	at com.tencent.polaris.plugins.registry.memory.InMemoryRegistry$SavePersistTask.run(InMemoryRegistry.java:581) [registry-memory-1.12.9.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_231]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_231]

2023-06-15 16:44:31.465 [ERROR] [service-identity] [] [] [] [] c.t.p.p.r.memory.MessagePersistHandler   :fail to write file .\polaris\backup\svc#dev#service-identity#routing.yaml.tmp

com.google.protobuf.InvalidProtocolBufferException: Cannot find type for url: type.googleapis.com/v1.RuleRoutingConfig
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printAny(JsonFormat.java:882) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.access$1000(JsonFormat.java:710) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl$1.print(JsonFormat.java:783) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:762) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1258) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1123) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1048) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1026) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:765) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1258) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1123) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printRepeatedFieldValue(JsonFormat.java:1062) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1046) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1026) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:765) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1258) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1123) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1048) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1026) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:765) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$Printer.appendTo(JsonFormat.java:368) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$Printer.print(JsonFormat.java:378) ~[protobuf-java-util-3.21.7.jar:na]
	at com.tencent.polaris.plugins.registry.memory.MessagePersistHandler.doWriteTmpFile(MessagePersistHandler.java:207) [registry-memory-1.12.9.jar:na]
	at com.tencent.polaris.plugins.registry.memory.MessagePersistHandler.writeTmpFile(MessagePersistHandler.java:193) [registry-memory-1.12.9.jar:na]
	at com.tencent.polaris.plugins.registry.memory.MessagePersistHandler.doSaveService(MessagePersistHandler.java:229) [registry-memory-1.12.9.jar:na]
	at com.tencent.polaris.plugins.registry.memory.MessagePersistHandler.saveService(MessagePersistHandler.java:144) [registry-memory-1.12.9.jar:na]
	at com.tencent.polaris.plugins.registry.memory.InMemoryRegistry$SavePersistTask.run(InMemoryRegistry.java:581) [registry-memory-1.12.9.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_231]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_231]

2023-06-15 16:44:31.465 [ERROR] [service-identity] [] [] [] [] c.t.p.p.r.memory.MessagePersistHandler   :fail to persist service ServiceEventKey{serviceKey=ServiceKey{namespace='dev', service='service-identity'}, eventType=ROUTING} after retry 2
2023-06-15 16:44:31.465 [ INFO] [service-identity] [] [] [] [] c.t.p.p.r.memory.MessagePersistHandler   :start to save service ServiceEventKey{serviceKey=ServiceKey{namespace='dev', service='service-user'}, eventType=ROUTING}
2023-06-15 16:44:31.467 [ERROR] [service-identity] [] [] [] [] c.t.p.p.r.memory.MessagePersistHandler   :fail to write file .\polaris\backup\svc#dev#service-user#routing.yaml.tmp

com.google.protobuf.InvalidProtocolBufferException: Cannot find type for url: type.googleapis.com/v1.RuleRoutingConfig
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printAny(JsonFormat.java:882) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.access$1000(JsonFormat.java:710) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl$1.print(JsonFormat.java:783) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:762) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1258) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1123) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1048) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1026) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:765) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1258) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1123) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printRepeatedFieldValue(JsonFormat.java:1062) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1046) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1026) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:765) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1258) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1123) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1048) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1026) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:765) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$Printer.appendTo(JsonFormat.java:368) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$Printer.print(JsonFormat.java:378) ~[protobuf-java-util-3.21.7.jar:na]
	at com.tencent.polaris.plugins.registry.memory.MessagePersistHandler.doWriteTmpFile(MessagePersistHandler.java:207) [registry-memory-1.12.9.jar:na]
	at com.tencent.polaris.plugins.registry.memory.MessagePersistHandler.writeTmpFile(MessagePersistHandler.java:193) [registry-memory-1.12.9.jar:na]
	at com.tencent.polaris.plugins.registry.memory.MessagePersistHandler.doSaveService(MessagePersistHandler.java:229) [registry-memory-1.12.9.jar:na]
	at com.tencent.polaris.plugins.registry.memory.MessagePersistHandler.saveService(MessagePersistHandler.java:144) [registry-memory-1.12.9.jar:na]
	at com.tencent.polaris.plugins.registry.memory.InMemoryRegistry$SavePersistTask.run(InMemoryRegistry.java:581) [registry-memory-1.12.9.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_231]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_231]

2023-06-15 16:44:31.469 [ERROR] [service-identity] [] [] [] [] c.t.p.p.r.memory.MessagePersistHandler   :fail to write file .\polaris\backup\svc#dev#service-user#routing.yaml.tmp

com.google.protobuf.InvalidProtocolBufferException: Cannot find type for url: type.googleapis.com/v1.RuleRoutingConfig
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printAny(JsonFormat.java:882) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.access$1000(JsonFormat.java:710) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl$1.print(JsonFormat.java:783) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:762) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1258) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1123) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1048) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1026) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:765) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1258) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1123) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printRepeatedFieldValue(JsonFormat.java:1062) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1046) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1026) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:765) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1258) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1123) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1048) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1026) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:765) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$Printer.appendTo(JsonFormat.java:368) ~[protobuf-java-util-3.21.7.jar:na]
	at com.google.protobuf.util.JsonFormat$Printer.print(JsonFormat.java:378) ~[protobuf-java-util-3.21.7.jar:na]
	at com.tencent.polaris.plugins.registry.memory.MessagePersistHandler.doWriteTmpFile(MessagePersistHandler.java:207) [registry-memory-1.12.9.jar:na]
	at com.tencent.polaris.plugins.registry.memory.MessagePersistHandler.writeTmpFile(MessagePersistHandler.java:193) [registry-memory-1.12.9.jar:na]
	at com.tencent.polaris.plugins.registry.memory.MessagePersistHandler.doSaveService(MessagePersistHandler.java:229) [registry-memory-1.12.9.jar:na]
	at com.tencent.polaris.plugins.registry.memory.MessagePersistHandler.saveService(MessagePersistHandler.java:144) [registry-memory-1.12.9.jar:na]
	at com.tencent.polaris.plugins.registry.memory.InMemoryRegistry$SavePersistTask.run(InMemoryRegistry.java:581) [registry-memory-1.12.9.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_231]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_231]

**Comment by chuntaojun** [comment]
这里看应该是polaris-java依赖的 spec 版本比较低的缘故导致的，我们会回退下控制面的修改，避免数据面刷此类错误日志

**Comment by MasterSJ** [comment]
好的, 某个版本处理了之后可以回复我一下吗? 感谢.

**Comment by chuntaojun** [comment]
> 好的, 某个版本处理了之后可以回复我一下吗? 感谢.

预计明天就可以正式对外发布1.17.2了

**Comment by MasterSJ** [comment]
ok
